FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build

WORKDIR /workspace
COPY "api.lpm/api.csproj" "/workspace"

RUN dotnet restore "api.csproj" -bl:/workspace/publish/restore.binlog
COPY "api.lpm" "/workspace"
RUN dotnet publish "api.csproj" -bl:/workspace/publish/publish.binlog -c Release -o "/workspace/publish" --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS runtime

WORKDIR /app
COPY --from=build /workspace/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "api.dll"]
